// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiFjT2FnvaTC-ND-oh4maUGI43F5TF22E',
    appId: '1:349373589361:web:3d5e287e709b266a0578d0',
    messagingSenderId: '349373589361',
    projectId: 'expense-tracker-63428',
    authDomain: 'expense-tracker-63428.firebaseapp.com',
    storageBucket: 'expense-tracker-63428.firebasestorage.app',
    measurementId: 'G-6BP14EH3R2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYvRbR-O7NHgduQIHRfjUxJ4GNhaZ--pA',
    appId: '1:349373589361:android:a852702aea516c780578d0',
    messagingSenderId: '349373589361',
    projectId: 'expense-tracker-63428',
    storageBucket: 'expense-tracker-63428.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBas2etzq5ulsT_1y2fI0yZD-Qlrn-bpXw',
    appId: '1:349373589361:ios:1d722ce9d39d03780578d0',
    messagingSenderId: '349373589361',
    projectId: 'expense-tracker-63428',
    storageBucket: 'expense-tracker-63428.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBas2etzq5ulsT_1y2fI0yZD-Qlrn-bpXw',
    appId: '1:349373589361:ios:1d722ce9d39d03780578d0',
    messagingSenderId: '349373589361',
    projectId: 'expense-tracker-63428',
    storageBucket: 'expense-tracker-63428.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiFjT2FnvaTC-ND-oh4maUGI43F5TF22E',
    appId: '1:349373589361:web:b25eebfc5deb2dbd0578d0',
    messagingSenderId: '349373589361',
    projectId: 'expense-tracker-63428',
    authDomain: 'expense-tracker-63428.firebaseapp.com',
    storageBucket: 'expense-tracker-63428.firebasestorage.app',
    measurementId: 'G-364YV6F5D8',
  );
}
